vehicle_param:
  simulation:
    simTimeStep: 0.01 

  geomModelType: "rectangular"
  collFootPrintType: "ellipse"
  vehLength: 0.58   
  vehWidth: 0.31           # in meters
  collisionFootPrint:
    majorAxis: 0.60
    minorAxis: 0.34
  NX: 5                 # number of states currently : x,y,yaw,vx,steering
  NU: 2                 # control acc,steering_dot
  sim_deltaT: 0.01             # state update time
  state_publish_deltaT: 0.05  # state publisher delta-time
  veh_width: 0.31           # in meters
  veh_length: 0.58   
  veh_wheel_radius: 0.35
  veh_wheelbase: 0.34
  mass: 1.0         # in kg
  initXPose: 1.0 # x-position (world frame)
  initYPose: 1.0 # y-position (world frame)
  initYaw: 0.0 # yaw
  initVx: 0.0 # longitudinal speed of vehicle
  initSf: 0.0 # front steering in radians
  initAcc: 0.0 # acceleration
  initSv:  0.0 # steering velocity
  integration:
    type: "rk4"
    integrationStepSize: 0.01 #rk4/euler integration time-step

